### ISSUE TITLE
 Undefined index: expiry_month upon saving card

### ISSUE THREAD

**Issue by abdokouta** [checkout/checkout-magento2-plugin#235]
{"0":"Notice: Undefined index: expiry_month in \/home\/magento\/public_html\/vendor\/checkoutcom\/magento2\/Model\/Vault\/VaultToken.php on line 64","1":"#1 CheckoutCom\\Magento2\\Model\\Vault\\VaultToken->create() called at [vend$

**Comment by abdokouta** [comment]
any update?

**Comment by david-fiaty-cko** [comment]
Hi @abdokouta, we're currently looking into this. We will get back to you asap with more information.

**Comment by david-fiaty-cko** [comment]
@abdokouta could you please confirm which version of the Checkout.com Magento 2 module you are using?

**Comment by abdokouta** [comment]
2.2.2 and for magento 2.3.4

**Comment by abdokouta** [comment]
and there is another issue showing in backend 
`Warning: count(): Parameter must be an array or an object that implements Countable in /home/magento/public_html/vendor/checkoutcom/magento2/Model/Service/VersionHandlerService.php on line 143
`

**Comment by luke-fenn-cko** [comment]
Hello
Thank you for raising this. We're currently still investigating your first issue.
 As for your second issue, this is something that has previously been noticed and the fix will be included in an upcoming release. However, if you would like to, you could get this fix by downloading the master version.
To do this, on the composer section of the module install, run:
`composer require checkoutcom/magento2:dev-master`

@abdokouta

> and there is another issue showing in backend
> `Warning: count(): Parameter must be an array or an object that implements Countable in /home/magento/public_html/vendor/checkoutcom/magento2/Model/Service/VersionHandlerService.php on line 143 `

**Comment by david-fiaty-cko** [comment]
@abdokouta, the second issue has a fix available on the master branch. Even though a new release hasn't been created yet, you can still download the latest fixes from the master branch.

**Comment by abdokouta** [comment]
@david-fiaty-cko @luke-fenn-cko thank you for ur collaborating. for the first issue it's important to us, cuz we need to offer saving cards so i will follow up

**Comment by luke-fenn-cko** [comment]
@abdokouta 

Hello,

A quick update on the status of this issue. We have identified the cause and are working on a fix.

As you mentioned, saved cards are needed for you. If you would like to offer the ability to save cards, while you wait for the fix to be released, then please make sure that in your checkout.com module configuration, under the 'Saved Card Payments' tab, that you have 'Use 3D Secure' set to 'No'. 

If you have any questions, don't hesitate to ask.

**Comment by abdokouta** [comment]
@luke-fenn-cko i have tried your solution and it says The payment card has been stored successfully. but upon refreshing the page nothing saved!

**Comment by abdokouta** [comment]
update please !?

**Comment by abdokouta** [comment]
@david-fiaty-cko @luke-fenn-cko is there any update?

**Comment by abdokouta** [comment]
@david-fiaty-cko @luke-fenn-cko any update about vault issue?

**Comment by david-fiaty-cko** [comment]
Hi @abdokouta, we have a fix implemented on the following branch: 
https://github.com/checkout/checkout-magento2-plugin/tree/github-card-issue

It's just going through QA now and we will hopefully be able to make it available asap this week. You will be notified as soon as the branch is confirmed functional.

In the meantime, feel free to test the branch if needed and let us know how it works for you. Please note that recompilation will be necessary to test this branch as dependency injections have been added to various classes.

**Comment by david-fiaty-cko** [comment]
@abdokouta, this issue should now be fixed in the 2.2.3 RC version:
https://github.com/checkout/checkout-magento2-plugin/tree/2.2.3-candidate

This is in now in active QA. You will be informed as soon as the official release is available but please feel free to test the RC.

**Comment by david-fiaty-cko** [comment]
@abdokouta, this issue should now be fixed in the 2.2.3 RC version:
https://github.com/checkout/checkout-magento2-plugin/tree/2.2.3-candidate

This is in now in active QA. You will be informed as soon as the official release is available but please feel free to test the RC.

**Comment by david-fiaty-cko** [comment]
@abdokouta, there is a new release with a fix for this issue:
https://github.com/checkout/checkout-magento2-plugin/releases/tag/2.2.3

**Comment by abdokouta** [comment]
okay, thank you @david-fiaty-cko i will let u know the updates, there is another issue in account tabs the stored cards tab duplicated and i have test it on another Magento setup and still the same even after the update to latest version of checkout.com, i have attached a screenshot.
<img width="1680" alt="Screen Shot 2020-04-06 at 11 34 03 PM" src="https://user-images.githubusercontent.com/12934929/78602494-384cb980-785f-11ea-95eb-2cd5f2819d61.png">

**Comment by abdokouta** [comment]
@david-fiaty-cko another issue https://beta.magento.pixiedia.com/en_sa/checkout_com/account/savecard/

`Exception #0 (Exception): Notice: Undefined offset: 1 in /home/magento/public_html/vendor/checkoutcom/magento2/Controller/Account/SaveCard.php on line 72
`

**Comment by abdokouta** [comment]
@david-fiaty-cko @luke-fenn-cko update please?

**Comment by david-fiaty-cko** [comment]
@abdokouta, fixes for this notice error and for the duplicated account link is available on the 2.2.4 RC branch:
https://github.com/checkout/checkout-magento2-plugin/tree/2.2.4-candidate

This branch is currently under QA. You will be informed as soon as there is a stable release but feel free to try the RC and give us your feedback.

**Comment by abdokouta** [comment]
@david-fiaty-cko, okay thank you. Waiting ...

**Comment by david-fiaty-cko** [comment]
@abdokouta, this issue should now be fixed on the latest 2.2.4 release:
https://github.com/checkout/checkout-magento2-plugin/releases/tag/2.2.4

You can try the release and close this issue if you're happy with it.
In the case you need to raise other matters, please open separate issues for each one of them rather than adding unrelated topics here.

**Comment by abdokouta** [comment]
@david-fiaty-cko thank you, it's working but i have one more question how can i save card in test environment i have tried and doing debugging and it returns 200 but the card not saved it says `The card could not be saved.`
