### ISSUE TITLE
Cannot change order status from pending to holded

### ISSUE THREAD

**Issue by Lukas713** [checkout/checkout-magento2-plugin#333]
We have installed checkout.com extension on magento 2 installation. When you create an order, the webhook will insert record inside `checkoutcom_webhooks` table. Newly, successful orders will get status `pending` (in our case). And when the order is edited to the status `holded`, the plugin `\CheckoutCom\Magento2\Plugin\Backend\OrderAfterSave::afterSave` is invoked. It will load the pre-inserted records from  `checkoutcom_webhooks` table and at the end, this method `\CheckoutCom\Magento2\Model\Service\TransactionHandlerService::setOrderStatus` will do the second status change to the order. After submiting order to status `holded`, plugin will change the status to `pending` again.

TL,TR:
vendor/checkoutcom/magento2/Model/Service/TransactionHandlerService.php:432 IS WRONG!

Regards,
Lukas

**Comment by akin-kayim-cko** [comment]
@Lukas713 thank you for raising this. For clairity, could you please confirm what the expected functionality is for the above use case.

**Comment by david-fiaty-cko** [comment]
@Lukas713 if you look at line 149 of the same file, you will see that there is condition checking if the code you're referring to should be executed: https://github.com/checkout/checkout-magento2-plugin/blob/5194e34cbc7f3d42155f02faaf23bf07fcea12fc/Model/Service/TransactionHandlerService.php#L149

The call chain will then lead to the line 432 you're referring to. This check says that the code should be executed only if the order has no transactions, and only if there is a webhook coming from the gateway to process.

Could you please elaborate on how your use case is impacted by this code despite the checks on line 149?

**Comment by brucemead** [comment]
Hi @david-fiaty-cko, we're experience this with one of clients too.

Replication Steps:
- Place order
- Ensure the order has the payment captured
- 'Hold' the order

Actual results
- Order remains in the original state and status

Expected results
- Order moves to the `state` = `holded` and `status` = `holded`

For us the issue is stemming from the `CheckoutCom\Magento2\Plugin\Backend\OrderAfterSave` undoing the `holded` change with the `CheckoutCom\Magento2\Model\Service\TransactionHandlerService::setOrderStatus` which is then trying to force the status to one which doesn't exist in the `holded` state and it all gets reverted.

Thanks,
Bruce

**Comment by brucemead** [comment]
My quick and dirty workaround so that our clients can use the hold feature:
```
--- checkoutcom/magento2/Plugin/Backend/OrderAfterSave.php	2020-09-23 20:45:28.476182022 +0100
+++ checkoutcom/magento2/Plugin/Backend/OrderAfterSave.php	2020-09-23 20:45:58.108687505 +0100
@@ -63,6 +63,13 @@
      */
     public function afterSave(OrderRepositoryInterface $orderRepository, $order)
     {
+        # https://github.com/checkout/checkout-magento2-plugin/issues/333
+        if ($order->hasHoldBeforeState()
+            && $order->getState() === 'holded'
+            && $order->getStatus() === 'holded') {
+            return $order;
+        }
+
         if ($this->backendAuthSession->isLoggedIn()) {
             // Get the method ID
             $methodId = $order->getPayment()->getMethodInstance()->getCode();
```
For `checkoutcom/magento2` version `2.2.6`

**Comment by Lukas713** [comment]
Exactly as @brucemead  explained. We have the same solution in our project. Its dirty but currently working.

**Comment by luke-fenn-cko** [comment]
Hi @Lukas713 & @brucemead,

I hope all is well.

We have released a new plugin version `2.2.7` with a fix to this. Please update if you can.

Thank you, 

Luke F

**Comment by Lukas713** [comment]
I see what you have done in 2.2.7. But the problem remains for the orders that are changed to status voided etc. You must fix the source of the problem. And the source problem that plugin is changing the order status after changing the order status.  `\CheckoutCom\Magento2\Model\Service\TransactionHandlerService::setOrderStatus` should be fixed in a way that when my order is changed to pending, it should stay as pending. Your overrided function in my project looks like this:

`public function afterSave(OrderRepositoryInterface $orderRepository, $order)
    {
        if ($this->backendAuthSession->isLoggedIn()) {
            // Get the method ID
            $methodId = $order->getPayment()->getMethodInstance()->getCode();

            // Process the webhooks
            if (in_array($methodId, $this->config->getMethodsList())) {
                $status = $order->getStatus();
                if ($status === 'holded' || $status === $this->config->getValue('order_status_voided')) {
                    return $order;
                }

                $this->webhookHandler->processAllWebhooks($order);
            }
        }

        return $order;
    }`

**Comment by alexryall** [comment]
It doesn't make sense why the module tries to control the Magento order state and status at every opportunity as out-the-box Magento will correctly set the state and status without custom payment method code. With the latest version 2.2.7 it introduces a new bug where order states are stuck as "processing" instead of "complete" after the payment is captured, and this even affects other non-checkout.com payment methods.

I hope in the next version all this code is removed to let Magento do its thing!

**Comment by luke-fenn-cko** [comment]
Hello,

We have released version 2.2.8 with a fix for this issue, thank you for your patience in waiting for this version.

> I hope in the next version all this code is removed to let Magento do its thing!

Also, we are currently performing a full audit of our module to make sure it follows Magento best practices which includes coupling more tightly with the default Magento order flow and as you correctly suggest: "let Magento do its thing!"

Many Thanks,

Luke

**Comment by luke-fenn-cko** [comment]
Closing this issue as there has been no update.
